### ISSUE TITLE
Issue NameError

### ISSUE THREAD

**Issue by IZ-US1** [dfaram7/zeroshot_amitt#1]
Hi @dfaram7 ! First of all, thank you very much for doing this (I´m researching about disinfo for my master´s thesis)
 It seems like there is an issue. Till now I´ve 1st) converted the file to .py, 2nd) installed anaconda and all the modules required.
The issue appears when initiating the file, suddenly stops and shows this message:
Traceback (most recent call last):
  File "/home/kali/Downloads/zero_shot_amitt.py", line 86, in <module>
    data = googlescrape(yoursearchtermhere, 15)
NameError: name 'yoursearchtermhere' is not defined
Same error occurs in JN:
![imagen](https://user-images.githubusercontent.com/98294466/150722983-070ed9c5-1a79-4481-b8bb-a8161bb3ff18.png)

Looking for other errors using JN, this appeared also
![imagen](https://user-images.githubusercontent.com/98294466/150723462-6cca8cb2-05f2-420d-9ff6-98f114f53f93.png)

**Comment by dfaram7** [comment]
Thanks for checking the project out!

Hopefully this is a fairly easy issue to resolve. yoursearchtermhere needs to be replaced with a string of your choice, "US elections" or whichever specific disinformation campaign you are researching for your thesis.

Once doing the above, data will then be declared correctly and everything should work.

**Comment by dfaram7** [comment]
I'm going to close this issue now, feel free to open up another if you are still having trouble.
